### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by wildermuthn** [wwwtyro/node-ovrsdk#3]
When I run this, I get "Uncaught TypeError: error setting argument 1 - value is out of bounds". The error occurs at this line:

> ibovr.ovrHmd_StartSensor(hmd, libovr.ovrHmdCap_Orientation, libovr.ovrHmdCap_Orientation);

My rift is plugged in, and works fine. I had some trouble installing node-ovrsdk until I got Python and Visual Studio installed. I did receive some warnings on the install of node-ovrsdk, however:

> Building the projects in this solution one at a time. To enable parallel build,
> please add the "/m" switch.
>   binding.cc
> c:\users\home.nw-gyp\0.8.6\src\node.h(124): warning C4996: 'v8::FunctionTempla
> te::New': was declared deprecated [C:\Users\Home\Desktop\oc-2\app\node_modules\
> node-ovrsdk\node_modules\ref\build\binding.vcxproj]
>           C:\Users\Home.nw-gyp\0.8.6\deps\v8\include\v8.h(3343) : see declarat
>   ion of 'v8::FunctionTemplate::New'
>           ..\src\binding.cc(641) : see reference to function template instantia
>   tion 'void node::SetMethodv8::Handle<T>(target_t,const char *,v8::Invocatio
>   nCallback)' being compiled
>           with
>           [
>               T=v8::Object,
>               target_t=v8::Handlev8::Object
>           ]
> C:\Users\Home.nw-gyp\0.8.6\deps\v8\include\v8.h(261): warning C4506: no defini
> tion for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T
> )' [C:\Users\Home\Desktop\oc-2\app\node_modules\node-ovrsdk\node_modules\ref\b
> uild\binding.vcxproj]
>           with
>           [
>               T=v8::Object
>           ]
>      Creating library C:\Users\Home\Desktop\oc-2\app\node_modules\node-ovrsdk\n
>   ode_modules\ref\build\Release\binding.lib and object C:\Users\Home\Desktop\oc
>   -2\app\node_modules\node-ovrsdk\node_modules\ref\build\Release\binding.exp
>   Generating code
>   Finished generating code
>   binding.vcxproj -> C:\Users\Home\Desktop\oc-2\app\node_modules\node-ovrsdk\no
>   de_modules\ref\build\Release\binding.node
> gyp info ok

I've got nodewebkit running my little rift app with threejs and the rift effect working just fine. If I get over this hurdle, I'll be in great shape. Thanks!

**Comment by wwwtyro** [comment]
My bad, I forgot to update the docs.

ovrHmdCap_Orientation was changed to ovrSensorCap_Orientation between 0.3.1 and 0.3.2.

**Comment by wildermuthn** [comment]
Worked!! :)—
